from . import project_sub_update_wizard
from . import analytic_transfer_wizard
from . import project_update
from . import analytic_account
from . import project_task
from . import project
from . import sale_line
from . import project_sub_update
from . import sale_order
from . import project_tags
from . import res_partner
from . import supervisor
from . import pending_service
from . import employee